// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherAPI.Repository;

#nullable disable

namespace WeatherAPI.Migrations
{
	[DbContext(typeof(WeatherDbContext))]
	partial class WeatherDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "10.0.10")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("WeatherAPI.Models.Temperature", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<int>("MaxTemp")
						.HasColumnType("integer");

					b.Property<int>("MinTemp")
						.HasColumnType("integer");

					b.Property<string>("Month")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("Temperatures");

					b.HasData(
						new
						{
							Id = 1,
							MaxTemp = 6,
							MinTemp = 1,
							Month = "January"
						},
						new
						{
							Id = 2,
							MaxTemp = 7,
							MinTemp = 1,
							Month = "February"
						},
						new
						{
							Id = 3,
							MaxTemp = 10,
							MinTemp = 3,
							Month = "March"
						},
						new
						{
							Id = 4,
							MaxTemp = 14,
							MinTemp = 5,
							Month = "April"
						},
						new
						{
							Id = 5,
							MaxTemp = 18,
							MinTemp = 9,
							Month = "May"
						},
						new
						{
							Id = 6,
							MaxTemp = 21,
							MinTemp = 12,
							Month = "June"
						},
						new
						{
							Id = 7,
							MaxTemp = 23,
							MinTemp = 14,
							Month = "July"
						},
						new
						{
							Id = 8,
							MaxTemp = 23,
							MinTemp = 14,
							Month = "August"
						},
						new
						{
							Id = 9,
							MaxTemp = 19,
							MinTemp = 11,
							Month = "September"
						},
						new
						{
							Id = 10,
							MaxTemp = 15,
							MinTemp = 8,
							Month = "October"
						},
						new
						{
							Id = 11,
							MaxTemp = 10,
							MinTemp = 4,
							Month = "November"
						},
						new
						{
							Id = 12,
							MaxTemp = 7,
							MinTemp = 2,
							Month = "December"
						});
				});
#pragma warning restore 612, 618
		}
	}
}
